include:
  - board: nice_nano
    shield: Pure42_left nice_view_adapter nice_view
  - board: nice_nano 
    shield: Pure42_right nice_view_adapter nice_view
  - board: nice_nano
    shield: settings_reset
